### ISSUE TITLE
preprocess

### ISSUE THREAD

**Issue by assyoucan** [leimao/Voice_Converter_CycleGAN#11]
您好，预处理过程中的函数world_encode_spectral_envelop我看到您的备注是# Get Mel-cepstral coefficients (MCEPs)，得到的coded_sp就等同于mcep了么，此外我还注意到您用了librosa提取mfcc但是没有使用它，这是为什么呢

**Comment by leimao** [comment]
In this particular project, the features we used are MCEPs instead of MFCCs.

**Comment by assyoucan** [comment]
> 在这个特定项目中，我们使用的功能是MCEP而不是MFCC。

好的感谢，那么得到的coded_sp就是mcep么

**Comment by leimao** [comment]
It is. MFCCs were never used.
