### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by ghost** [leimao/Voice_Converter_CycleGAN#12]
Dear sir,
I was trying to implement your code on my dataset and after a certain time interval the training stopped. Is there any way to resume the training from the last model saved?
Or are there any way to save the models at different epochs?
Please help

**Comment by leimao** [comment]
Hi Kunal,

The `CycleGAN` class does have a `load` method which allows loading of the saved models for continue training. But I did not implement a demo of continue training in this particular project. For your reference, if you want to implement a continue training script, you can take a look at a file that I implemented for another project. 
Here is the link: https://github.com/leimao/DLSS_ESPCN/blob/master/train_continue.py

Best,
Lei

**Comment by ghost** [comment]
Thank you so much

**Comment by leimao** [comment]
It is nothing special but loading the saved model and keeping on training. I apologize that I don't have time to do this in person.

**Comment by drat** [comment]
> Hi Kunal,
> 
> The `CycleGAN` class does have a `load` method which allows loading of the saved models for continue training. But I did not implement a demo of continue training in this particular project. For your reference, if you want to implement a continue training script, you can take a look at a file that I implemented for another project.
> Here is the link: https://github.com/leimao/DLSS_ESPCN/blob/master/train_continue.py
> 
> Best,
> Lei
Dear Leimao,
The link you provided is no longer accessible, can you renew the link? 
Thank you
