### ISSUE TITLE
Using the voice converter for French

### ISSUE THREAD

**Issue by Wajih88** [leimao/Voice_Converter_CycleGAN#22]
Hi Lei Mao,

I was wondering if I can use your architecture for voice conversion for French and if it's the case what data base should I use for the training.

Looking forward for your answer,

**Comment by leimao** [comment]
Hi @Wajih88 ,
You are welcome to test the model for any dataset. I have not been looking into the datasets so I am probably not the best person to ask. Ideally, any speech dataset consisting of speeches from different people should work. You can even prepare the dataset on your own. Record your mum's and dad's voice, and try it out using the model to see what will happen. 
Best,
Lei

**Comment by Wajih88** [comment]
Thank you for your answer @leimao 
I've just noticed that the data in the vcc 2016 is parallel. So does my data have to be parallel too ? Also, what I'm trying to achieve is multi source conversion to one target voice. So is this possible with your method ?
Looking forward for your answer,

**Comment by leimao** [comment]
The dataset was parallel but it was used in a non-parallel way.
