### ISSUE TITLE
Why not ues the cross_entropy_loss

### ISSUE THREAD

**Issue by sqsqsqthu** [leimao/Voice_Converter_CycleGAN#32]
In the paper: 
CycleGAN-VC: Non-parallel Voice Conversion Using Cycle-Consistent Adversarial Networks
we coule see that  Adversarial loss  is calculated by the cross _entropy_loss, whereas in your code, i see L2_loss  in  Adversarial loss, so don't you use the cross _entropy_loss?
Thanks for your answer~Hoping for your guidance

**Comment by leimao** [comment]
It has been a while but I think I remember they specifically mentioned that they were using the least square GAN trick in the paper.

**Comment by sqsqsqthu** [comment]
Thanks for your answer
