### ISSUE TITLE
AttributeError about tf.contrib.layers.instance_norm

### ISSUE THREAD

**Issue by MorganCZY** [leimao/Voice_Converter_CycleGAN#6]
When i run "train.py", an attribute error, "AttributeError: module 'tensorflow.contrib.layers' has no attribute 'instance_norm'", occurs to me because "tf.contrib.layers.instance_norm" is used. But i can't find instance_norm in the path"tensorflow/contrib/layers/" even in the 1.8.0 version. Could you give me some instructions?

**Comment by leimao** [comment]
I checked my TensorFlow environment and it is 1.8.0.
```
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>import tensorflow as tf
>>>tf.__version__
'1.8.0'
```

According to the TensorFlow official API for 1.8, there is [instance norm](https://www.tensorflow.org/versions/r1.8/api_docs/python/tf/contrib/layers/instance_norm) layer implemented.
So I think your TensorFlow is old version and should be upgraded to run the program.
Although tf.contrib will likely be removed or relocated in the coming TensorFlow 2.0, I do think the instance norm will be kept somewhere.

**Comment by MorganCZY** [comment]
The model has successfully been training after I update the tensorflow version. However, the training stopped at the 428th epoch shown as the following picture. I didn't find where and in which case the code would print "Terminated".
![error](https://user-images.githubusercontent.com/33675916/44440065-14405400-a5f9-11e8-8892-48aecfe0260a.png)

**Comment by leimao** [comment]
Try to see if the problem is reproducible.

**Comment by MorganCZY** [comment]
I' ve successfully run the code and been very impressed with the good effects of converted voices. However, the current model is designed as one-to-one voice conversion. In the training phase, the source and target should be assigned and only this pair voices can be converted bidirectionally. I wonder if it is possible for this code project to do many-to-one voice conversion after some modifications? If it is, could you give me some instructions?

**Comment by leimao** [comment]
At least for this particular project, it is only restricted to one-to-one conversion. There are many efforts of the GAN community trying to do many-to-many conversions. Please check the latest papers out.
